function out = computepServices(pwt, pSectoral, pBase, parameters)

alpha = parameters.alpha;
iServices = parameters.iServices;

[nCountries, nSectors, nYears] = size(pSectoral);
   

out = zeros(nCountries, nYears);

for t = 1:nYears
    for n = 1:nCountries
        out(n, t) = ...
            (pwt(t, n) * pBase(t))^(1 / alpha(iServices, t)) * ...
            prod(alpha(:, t).^(- alpha(:, t)))^(- 1 / alpha(iServices, t)) * ...
            prod(pSectoral(n, 1:(nSectors - 1), t) .^ ...
                 (alpha(1:(nSectors - 1), t)'))^(- 1 / alpha(iServices, t));
    end % n 
end % t 

% out = ...
%     ((pwt .* repmat(pBase, [1 nCountries]))').^(1 / alpha(iServices)) .* ...
%     pBase(1).^( - 1 / alpha(iServices)) .* ...
%     squeeze(prod(pSectoral(1:nCountries, 1:(nSectors - 1), :) .^ ...
%                  repmat(alpha(1:(nSectors - 1))', [nCountries 1 nYears]), 2)) .^ ...
%             (- 1 / alpha(iServices));

end